### ISSUE TITLE
DB table 추가 생성 - 1 :loudspeaker:

### ISSUE THREAD

**Issue by Liiims** [KOSTA224-semiproject1/semi-project-moco#76]
:star2: DB에 moco_scrap 테이블 생성해주세요 :star2:

-- 스크랩 table 생성 sql 
create table moco_scrap (
  email varchar2(100) not null,
  post_no number not null,
  scrap_date date not null,
  constraint fk_email foreign key(email) references moco_member(email),
  constraint fk_post_no foreign key(post_no) references moco_qna_board(post_no)
);

--insert into moco_scrap values('test@naver.com', 1, sysdate);
--insert into moco_scrap values('test@naver.com', 2, sysdate);

commit -- 꼭 해줘야함!

-- email이 'test@naver.com' 인 회원이 스크랩한 정보 조회 sql
-- sub query >>  moco_srap와 moco_member와 email이 일치하는것 중 특정 email 인 것을 찾음
select v.rnum, v.post_no, b.post_title, to_char(b.post_regdate, 'yyyy-mm-dd') as post_regdate, v.nickname, b.hits
from (
    select row_number() over(order by s.scrap_date desc) as rnum, m.email, m.nickname, s.post_no, s.scrap_date
    from moco_member m, moco_scrap s 
    where m.email=s.email and m.email='' 
) v, moco_qna_board b
where v.post_no=b.post_no 
and v.rnum between 1 and 5;	
-- 찾은 게시물 정보 중 moco_qna_board post 정보를 찾음

-- checkScrap test sql
select count(*) from moco_scrap where post_no = 1 and email = 'test@naver.com';

**Comment by cheoljin408** [comment]
@Liiims 
- 본 쿼리에 m.nicknam -> v.nickname 수정 해놨음.
- 서브 쿼리에 email='' 빈칸으로 수정 해놨음.
