### ISSUE TITLE
DB table 추가 생성 - 2 📢

### ISSUE THREAD

**Issue by joonkb** [KOSTA224-semiproject1/semi-project-moco#80]
사용자 마다 테마를 변경할 수 있고 이를 로그아웃시 테마 정보를 유지하기 위해서 컬럼을 불가피하게 추가시켰습니다.
moco_member 테이블에 thema 컬럼을 추가시킵시다!

명령어는 다음과 같습니다
alter table moco_member add thema varchar(25) default 'duotone-light' not null;

duotone-light 의 경우 기본테마 속성으로 default로 지정하였습니다.

**Comment by joonkb** [comment]
사용자 마다 테마를 변경할 수 있고 이를 로그아웃시 테마 정보를 유지하기 위해서 컬럼을 불가피하게 추가시켰습니다.
moco_member 테이블에 `thema` 컬럼을 추가시킵시다!

명령어는 다음과 같습니다
**alter table moco_member add thema varchar(25) default 'duotone-light' not null;**

_duotone-light_ 의 경우 `기본테마` 속성으로 default로 지정하였습니다.

**Comment by Liiims** [comment]
확인했습니다!
